### ISSUE TITLE
the CustomRequest that method is wc_exchangeKey should filtered 

### ISSUE THREAD

**Issue by SephirothLT** [WalletConnect/kotlin-walletconnect-lib#10]
the CustomRequest that method is wc_exchangeKey should filtered 

detali:
Custom(id=1557730797842490, method=wc_exchangeKey, params=[{peerId=60dfeecf-e905-41d9-a002-2222895a1265, peerMeta={description=, url=https://testnet.binance.org, icons=[https://testnet.binance.org/favicon.png, https://testnet.binance.org/favicon.png], name=Binance - | Dex Trading | Decentralized Exchange | Binance.org}, nextKey=ec768644e1c09eae44e5ca31f893dd485e3c210a9c1625d3ec738f96b946d819}])

**Comment by rmeissner** [comment]
It would be nice to know where it should be filtered and why you think it should be filtered (motivation to change the existing behaviour)

**Comment by pedrouid** [comment]
Hey @rmeissner, it's actually part of the WalletConnect reserved methods, therefore the SDK should handle them accordingly (or dismiss them if the feature is not implemented.

You can see it [here](https://github.com/WalletConnect/walletconnect-monorepo/blob/e9e51c8dd487141b4e972b9c24209b002791dba2/packages/core/src/events.ts#L66) on the walletconnect-monorepo. But perhaps it would be better to filter any `wc` namespaced method instead, since they are guaranteed to be WalletConnect specific.

**Comment by ligi** [comment]
I thought we removed exchange key? What does filter actually mean - not react at all or report an error? If an error - which one?

**Comment by pedrouid** [comment]
Filter them so that they don't trigger the `call_request` event

**Comment by ligi** [comment]
OK - that should then really make it's way into the documentation. Btw. just made a PR to the documentation repository as this still was referring to the old flow which was dropped.
